name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    uses: groundsgg/.github/.github/workflows/release-please.yml@main
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
