name: Publish Release Packages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    uses: groundsgg/.github/.github/workflows/gradle-publish.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
